### ISSUE TITLE
White blank screen during startup

### ISSUE THREAD

**Issue by Mercury-ThePlanet** [ChayoteJarocho/web-page-screensaver#5]
Hi, the screensaver works well during debug and during windows Preview.
However, when it actually starts as a screen saver (i.e. after a while of inactivity), it just shows a blank screen instead of the desired website.
May I know if someone else has the same issue?

**Comment by Mercury-ThePlanet** [comment]
Error message received

Also, I received this error message from the Edge program just now.

---
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.Navigate(String uri)
   at Microsoft.Web.WebView2.Core.CoreWebView2.Navigate(String uri)
   at WebPageScreensaver.ScreensaverForm.BrowseTo(String url)
   at WebPageScreensaver.ScreensaverForm.RotateSite()
   at WebPageScreensaver.ScreensaverForm.<ScreensaverForm_Load>b__9_0(Object s, EventArgs ee)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Private.CoreLib.dll
----------------------------------------
WebPageScreensaver
    Assembly Version: 2.0.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.2.0
    Win32 Version: 5.0.220.61301
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.2.0
    Win32 Version: 5.0.220.61301
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Diagnostics.Process.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Collections.NonGeneric.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/Microsoft.Win32.Registry.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Runtime.Extensions.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Linq.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.220.61301
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/Accessibility.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Private.Uri.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Memory.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Threading.Tasks.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/mscorlib.dll
----------------------------------------
WindowsBase
    Assembly Version: 5.0.2.0
    Win32 Version: 5.0.220.61302
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.2/WindowsBase.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Buffers.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.ComponentModel.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Reflection.Metadata.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.IO.FileSystem.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.220.61120
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.2/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
```
---

**Comment by Mercury-ThePlanet** [comment]
Updates
After republishing, it now works on one of my monitors, but not the other one

**Comment by ChayoteJarocho** [comment]
Sorry I missed your issue, @Mercury-ThePlanet . I'm glad it now works in one monitor. I currently don't have a second monitor but as soon as I get one, I'll try to debug the issue and address the problem you reported.

**Comment by ChayoteJarocho** [comment]
Just to be sure you got a chance to configure it correctly, what options did you choose in the Settings window to ensure it would show up in all your monitors?

**Comment by Mercury-ThePlanet** [comment]
Hi, sorry for my late reply. I was a bit busy with college assignments back then

Originally I used the "span" option, and the website showed across two screens correctly. However, when I go switch to the "Mirror" or "Seperate" option, one screen would should a blank page instead.
One thing to note is that all the above mode works well in the "test" mode, and that the white screen only showed up when the screensaver is initiated by windows.

**Comment by Mercury-ThePlanet** [comment]
I recevied the following error after upgraded to 2.0.2


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
```
************** Exception Text **************
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.Navigate(String uri)
   at Microsoft.Web.WebView2.Core.CoreWebView2.Navigate(String uri)
   at WebPageScreensaver.ScreensaverForm.BrowseTo(String url)
   at WebPageScreensaver.ScreensaverForm.RotateSite()
   at WebPageScreensaver.ScreensaverForm.<ScreensaverForm_Load>b__9_0(Object s, EventArgs ee)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WebPageScreensaver
    Assembly Version: 2.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.4.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.4.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.774.44
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.774.44
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------

************** JIT Debugging **************
```
